version: "3.8"
services:
  database:
    image: postgres:latest
    ports:
      - 6543:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shaPostgres
      POSTGRES_DB: postgres
  #stock:
  #  image: stock:0.0.1-SNAPSHOT
  #  depends_on:
  #    - database
  #  ports:
  #    - 8080:8080
